### PR TITLE
Updated API url

### PR DESCRIPTION
**Pull request by longhotsummer**
Open By-laws content is moving to the Laws.Africa platform.

### CODE REVIEW

**Comment by longhotsummer** [comment]
@jbothma @ebsuku

**Comment by longhotsummer** [comment]
@ebsuku @jbothma this is failing and I'm not sure why, I suspect it has to do with the encrypted travis token. I don't have write perms to this repo, so I can't see the token and my builds just don't inject the token.

Would it be possible to grant me write access to this repo so I can debug? Alternative is to debug with you together.

**Comment by knightebsuku** [comment]
@longhotsummer 

Could this be related? 
https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by longhotsummer** [comment]
From their docs "Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code."

So that means I can't test that this build works correctly, because my branch is in a separate repo because I don't have push perms for this repo. So that means that my travis builds won't get the encrypted variables, so the build will always fail.

If you give me write access to the repo I can ensure it's doing the right thing.

**Comment by knightebsuku** [comment]
@longhotsummer 

You should have access.

**Comment by longhotsummer** [comment]
Fixed in master.

**Pull request closed without merging**
